name: rlproject
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib=3.1.0
  - numpy=1.19
  - python=3.7.3
  - scipy=1.3.0
  - seaborn=0.9.0
  - tqdm=4.32.1
  - pyglet=1.3.2
  - pip=19.3
  - pip:
    - gym==0.10.8
